name: Update Stock Predictions

on:
  schedule:
    - cron: '30 17 * * 1-5'  # Run at 5:30 PM on weekdays
  workflow_dispatch:  # Allow manual triggers

jobs:
  update-predictions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f my-react-app/backend/requirements-github.txt ]; then
            pip install -r my-react-app/backend/requirements-github.txt
          else
            pip install pandas numpy joblib yfinance scikit-learn xgboost firebase-admin
          fi
      
      - name: Create Firebase service account file
        env:
          FIREBASE_SERVICE_ACCOUNT_JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: |
          echo "$FIREBASE_SERVICE_ACCOUNT_JSON" > my-react-app/backend/firebase-service-account.json
          echo "Created Firebase service account file with size: $(wc -c my-react-app/backend/firebase-service-account.json)"
      
      - name: Run update script
        run: |
          cd my-react-app/backend
          python -m update_predictions
      
      - name: Log completion
        run: echo "Stock predictions updated successfully at $(date)"
